# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(796, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame#frame_4{border-top-left-radius:0px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"\n"
"    background-color: rgb(241, 244, 249)\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_home = QtWidgets.QFrame(self.frame_4)
        self.frame_home.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home.setObjectName("frame_home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_home)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_show = QtWidgets.QFrame(self.frame_home)
        self.frame_show.setStyleSheet("QFrame#frame_show{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_show)
        self.verticalLayout_11.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_Title = QtWidgets.QLabel(self.frame_show)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout_11.addWidget(self.label_Title)
        self.horiLay_car = QtWidgets.QHBoxLayout()
        self.horiLay_car.setSpacing(12)
        self.horiLay_car.setObjectName("horiLay_car")
        self.frame_carA = QtWidgets.QFrame(self.frame_show)
        self.frame_carA.setStyleSheet("\n"
"QFrame#frame_carA{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(162, 129, 247),  stop:1 rgb(119, 111, 252));\n"
"border: 1px outset rgb(98, 91, 213);\n"
"}\n"
"")
        self.frame_carA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carA.setObjectName("frame_carA")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_carA)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_carAUp = QtWidgets.QFrame(self.frame_carA)
        self.frame_carAUp.setStyleSheet("border:none")
        self.frame_carAUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carAUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carAUp.setObjectName("frame_carAUp")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_carAUp)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_carA = QtWidgets.QPushButton(self.frame_carAUp)
        self.btn_carA.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_carA.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_carA.setFont(font)
        self.btn_carA.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.btn_carA.setObjectName("btn_carA")
        self.horizontalLayout_6.addWidget(self.btn_carA)
        self.verticalLayout_2.addWidget(self.frame_carAUp)
        self.line_carA = QtWidgets.QFrame(self.frame_carA)
        self.line_carA.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_carA.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_carA.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_carA.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_carA.setObjectName("line_carA")
        self.verticalLayout_2.addWidget(self.line_carA)
        self.frame_carADown = QtWidgets.QFrame(self.frame_carA)
        self.frame_carADown.setStyleSheet("border:none")
        self.frame_carADown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carADown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carADown.setObjectName("frame_carADown")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_carADown)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_carAOs = QtWidgets.QLabel(self.frame_carADown)
        self.label_carAOs.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_carAOs.setFont(font)
        self.label_carAOs.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_carAOs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_carAOs.setObjectName("label_carAOs")
        self.verticalLayout_3.addWidget(self.label_carAOs, 0, QtCore.Qt.AlignBottom)
        self.label_carAMicro = QtWidgets.QLabel(self.frame_carADown)
        self.label_carAMicro.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_carAMicro.setFont(font)
        self.label_carAMicro.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_carAMicro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_carAMicro.setObjectName("label_carAMicro")
        self.verticalLayout_3.addWidget(self.label_carAMicro, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_carADown)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 1)
        self.horiLay_car.addWidget(self.frame_carA)
        self.frame_carB = QtWidgets.QFrame(self.frame_show)
        self.frame_carB.setStyleSheet("\n"
"QFrame#frame_carB{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border: 1px outset rgb(252, 194, 149)\n"
"}\n"
"")
        self.frame_carB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carB.setObjectName("frame_carB")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_carB)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_carBUp = QtWidgets.QFrame(self.frame_carB)
        self.frame_carBUp.setStyleSheet("border:none")
        self.frame_carBUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carBUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carBUp.setObjectName("frame_carBUp")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_carBUp)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_carB = QtWidgets.QPushButton(self.frame_carBUp)
        self.btn_carB.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_carB.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_carB.setFont(font)
        self.btn_carB.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.btn_carB.setObjectName("btn_carB")
        self.horizontalLayout_8.addWidget(self.btn_carB)
        self.verticalLayout_5.addWidget(self.frame_carBUp)
        self.line_carB = QtWidgets.QFrame(self.frame_carB)
        self.line_carB.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_carB.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_carB.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_carB.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_carB.setObjectName("line_carB")
        self.verticalLayout_5.addWidget(self.line_carB)
        self.frame_carBDown = QtWidgets.QFrame(self.frame_carB)
        self.frame_carBDown.setStyleSheet("border:none")
        self.frame_carBDown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carBDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carBDown.setObjectName("frame_carBDown")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_carBDown)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_CarBOs = QtWidgets.QLabel(self.frame_carBDown)
        self.label_CarBOs.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_CarBOs.setFont(font)
        self.label_CarBOs.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_CarBOs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CarBOs.setObjectName("label_CarBOs")
        self.verticalLayout_6.addWidget(self.label_CarBOs, 0, QtCore.Qt.AlignBottom)
        self.label_CarBMicro = QtWidgets.QLabel(self.frame_carBDown)
        self.label_CarBMicro.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_CarBMicro.setFont(font)
        self.label_CarBMicro.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_CarBMicro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CarBMicro.setObjectName("label_CarBMicro")
        self.verticalLayout_6.addWidget(self.label_CarBMicro, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.frame_carBDown)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 4)
        self.verticalLayout_5.setStretch(2, 1)
        self.horiLay_car.addWidget(self.frame_carB)
        self.frame_carC = QtWidgets.QFrame(self.frame_show)
        self.frame_carC.setStyleSheet("\n"
"QFrame#frame_carC{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(243, 175, 189),  stop:1 rgb(155, 118, 218));\n"
"border: 1px outset rgb(153, 117, 219)\n"
"}\n"
"")
        self.frame_carC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carC.setObjectName("frame_carC")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_carC)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_carCUp = QtWidgets.QFrame(self.frame_carC)
        self.frame_carCUp.setStyleSheet("border:none")
        self.frame_carCUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carCUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carCUp.setObjectName("frame_carCUp")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_carCUp)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_carC = QtWidgets.QPushButton(self.frame_carCUp)
        self.btn_carC.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_carC.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_carC.setFont(font)
        self.btn_carC.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.btn_carC.setObjectName("btn_carC")
        self.horizontalLayout_9.addWidget(self.btn_carC)
        self.verticalLayout_7.addWidget(self.frame_carCUp)
        self.line_carC = QtWidgets.QFrame(self.frame_carC)
        self.line_carC.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_carC.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_carC.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_carC.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_carC.setObjectName("line_carC")
        self.verticalLayout_7.addWidget(self.line_carC)
        self.frame_carCDown = QtWidgets.QFrame(self.frame_carC)
        self.frame_carCDown.setStyleSheet("border:none")
        self.frame_carCDown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carCDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carCDown.setObjectName("frame_carCDown")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_carCDown)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_CarCOs = QtWidgets.QLabel(self.frame_carCDown)
        self.label_CarCOs.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_CarCOs.setFont(font)
        self.label_CarCOs.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_CarCOs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CarCOs.setObjectName("label_CarCOs")
        self.verticalLayout_8.addWidget(self.label_CarCOs, 0, QtCore.Qt.AlignBottom)
        self.label_CarCMicro = QtWidgets.QLabel(self.frame_carCDown)
        self.label_CarCMicro.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_CarCMicro.setFont(font)
        self.label_CarCMicro.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_CarCMicro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CarCMicro.setObjectName("label_CarCMicro")
        self.verticalLayout_8.addWidget(self.label_CarCMicro, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.frame_carCDown)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 4)
        self.verticalLayout_7.setStretch(2, 1)
        self.horiLay_car.addWidget(self.frame_carC)
        self.frame_carD = QtWidgets.QFrame(self.frame_show)
        self.frame_carD.setStyleSheet("\n"
"QFrame#frame_carD{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(66, 226, 192),  stop:1 rgb(62, 154, 193));\n"
"border: 1px outset rgb(72, 158, 204)\n"
"}\n"
"")
        self.frame_carD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carD.setObjectName("frame_carD")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_carD)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_carDUp = QtWidgets.QFrame(self.frame_carD)
        self.frame_carDUp.setStyleSheet("border:none")
        self.frame_carDUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carDUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carDUp.setObjectName("frame_carDUp")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_carDUp)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_carD = QtWidgets.QPushButton(self.frame_carDUp)
        self.btn_carD.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_carD.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(False)
        self.btn_carD.setFont(font)
        self.btn_carD.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        self.btn_carD.setObjectName("btn_carD")
        self.horizontalLayout_10.addWidget(self.btn_carD)
        self.verticalLayout_9.addWidget(self.frame_carDUp)
        self.line_carD = QtWidgets.QFrame(self.frame_carD)
        self.line_carD.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_carD.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_carD.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_carD.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_carD.setObjectName("line_carD")
        self.verticalLayout_9.addWidget(self.line_carD)
        self.frame_carDDown = QtWidgets.QFrame(self.frame_carD)
        self.frame_carDDown.setStyleSheet("border:none")
        self.frame_carDDown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carDDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carDDown.setObjectName("frame_carDDown")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_carDDown)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_carDOs = QtWidgets.QLabel(self.frame_carDDown)
        self.label_carDOs.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_carDOs.setFont(font)
        self.label_carDOs.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_carDOs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_carDOs.setObjectName("label_carDOs")
        self.verticalLayout_10.addWidget(self.label_carDOs)
        self.label_carDMicro = QtWidgets.QLabel(self.frame_carDDown)
        self.label_carDMicro.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_carDMicro.setFont(font)
        self.label_carDMicro.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_carDMicro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_carDMicro.setObjectName("label_carDMicro")
        self.verticalLayout_10.addWidget(self.label_carDMicro)
        self.verticalLayout_9.addWidget(self.frame_carDDown)
        self.verticalLayout_9.setStretch(1, 4)
        self.horiLay_car.addWidget(self.frame_carD)
        self.verticalLayout_11.addLayout(self.horiLay_car)
        self.vertLay_graph = QtWidgets.QVBoxLayout()
        self.vertLay_graph.setSpacing(0)
        self.vertLay_graph.setObjectName("vertLay_graph")
        self.logScrollArea = QtWidgets.QScrollArea(self.frame_show)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logScrollArea.sizePolicy().hasHeightForWidth())
        self.logScrollArea.setSizePolicy(sizePolicy)
        self.logScrollArea.setStyleSheet("")
        self.logScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.logScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.logScrollArea.setWidgetResizable(True)
        self.logScrollArea.setObjectName("logScrollArea")
        self.wid_logContent = QtWidgets.QWidget()
        self.wid_logContent.setGeometry(QtCore.QRect(0, 0, 751, 500))
        self.wid_logContent.setMinimumSize(QtCore.QSize(300, 500))
        self.wid_logContent.setStyleSheet("border:none;\n"
"\n"
"")
        self.wid_logContent.setObjectName("wid_logContent")
        self.logScrollArea.setWidget(self.wid_logContent)
        self.vertLay_graph.addWidget(self.logScrollArea)
        self.verticalLayout_11.addLayout(self.vertLay_graph)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_11.setStretch(2, 3)
        self.horizontalLayout_3.addWidget(self.frame_show)
        self.horizontalLayout_12.addWidget(self.frame_home)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_12.setStretch(0, 10)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_20.addWidget(self.frame)
        # MainWindow.setCentralWidget(self.centralwidget)
        verLay_temp = QtWidgets.QVBoxLayout()
        verLay_temp.addWidget(self.centralwidget)
        MainWindow.setLayout(verLay_temp)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title.setText(_translate("MainWindow", "测试日志"))
        self.btn_carA.setText(_translate("MainWindow", "测试车一号"))
        self.label_carAOs.setText(_translate("MainWindow", "操作系统:Linux"))
        self.label_carAMicro.setText(_translate("MainWindow", "主控芯片:STM32F7"))
        self.btn_carB.setText(_translate("MainWindow", "测试车二号"))
        self.label_CarBOs.setText(_translate("MainWindow", "操作系统:Linux"))
        self.label_CarBMicro.setText(_translate("MainWindow", "主控芯片:STM32F1"))
        self.btn_carC.setText(_translate("MainWindow", "空"))
        self.label_CarCOs.setText(_translate("MainWindow", "操作系统:空"))
        self.label_CarCMicro.setText(_translate("MainWindow", "主控芯片:空"))
        self.btn_carD.setText(_translate("MainWindow", "空"))
        self.label_carDOs.setText(_translate("MainWindow", "操作系统:空"))
        self.label_carDMicro.setText(_translate("MainWindow", "主控芯片:空"))
# import resources_rc
