# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgModule.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ImgModuleUi(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(513, 511)
        Frame.setStyleSheet("background-color:rgb(255,255,255);")
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(50, 160, 401, 291))
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(40, 30, 191, 91))
        self.frame.setStyleSheet("border-radius: 20px;\n"
"background-color:#FFFFFF;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(54)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #61B0FF")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(2,2,2,0.6)")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 10, 81, 32))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 51, 153,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"      text-align: center center;\n"
"} \n"
"/*鼠标放在按钮上方*/\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 51, 153,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"} \n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 51, 153,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"} ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(100, 50, 81, 32))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 153, 51,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"      text-align: center center;\n"
"} \n"
"/*鼠标放在按钮上方*/\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 153, 51,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"} \n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 153, 51,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"} ")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setGeometry(QtCore.QRect(240, 30, 211, 91))
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_2.setText(_translate("Frame", "18"))
        self.label_3.setText(_translate("Frame", "FPS"))
        self.pushButton_2.setText(_translate("Frame", "原始画面"))
        self.pushButton.setText(_translate("Frame", "目标检测"))
