# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(113, 109, 252), stop:1 rgb(164, 124, 255));\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setStyleSheet("background-color:rgb(115,111,255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_red = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_red.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_red.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_red.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(240, 108, 96);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_red.setText("")
        self.pushButton_red.setObjectName("pushButton_red")
        self.horizontalLayout.addWidget(self.pushButton_red)
        self.pushButton_yellow = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_yellow.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_yellow.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_yellow.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(227, 199, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_yellow.setText("")
        self.pushButton_yellow.setObjectName("pushButton_yellow")
        self.horizontalLayout.addWidget(self.pushButton_yellow)
        self.pushButton_green = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_green.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_green.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_green.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(4, 180, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_green.setText("")
        self.pushButton_green.setObjectName("pushButton_green")
        self.horizontalLayout.addWidget(self.pushButton_green)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_2)
        self.label_theme = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_theme.setFont(font)
        self.label_theme.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_theme.setObjectName("label_theme")
        self.verticalLayout.addWidget(self.label_theme)
        self.listWidget_static = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_static.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_static.setMaximumSize(QtCore.QSize(16777, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.listWidget_static.setFont(font)
        self.listWidget_static.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(255, 255, 255,200);\n"
"    background-color: transparent\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"padding-left:12px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(130, 117, 255, 87);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    background-color: rgba(187, 170, 254,150);\n"
"    color: rgba(255, 255, 255,255);\n"
"border-left: 2px solid rgb(255, 255, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.listWidget_static.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_static.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_static.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_static.setAutoScrollMargin(16)
        self.listWidget_static.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_static.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_static.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_static.setMovement(QtWidgets.QListView.Static)
        self.listWidget_static.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_static.setProperty("isWrapping", False)
        self.listWidget_static.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_static.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_static.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_static.setModelColumn(0)
        self.listWidget_static.setBatchSize(100)
        self.listWidget_static.setProperty("IconSize", QtCore.QSize(128, 128))
        self.listWidget_static.setObjectName("listWidget_static")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/温室房_green-house.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget_static.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/沟通_communication.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_static.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/个人隐私_personal-privacy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_static.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/文档架子_document-folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget_static.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/交叉环_cross-ring.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget_static.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_static)
        self.label_realtime = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_realtime.setFont(font)
        self.label_realtime.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:12px;")
        self.label_realtime.setObjectName("label_realtime")
        self.verticalLayout.addWidget(self.label_realtime)
        self.listWidget_dynamic = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_dynamic.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_dynamic.setMaximumSize(QtCore.QSize(16777, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.listWidget_dynamic.setFont(font)
        self.listWidget_dynamic.setStyleSheet("QListView {\n"
"    border-radius: 20px;\n"
"    color: rgba(255, 255, 255,200);\n"
"    background-color: transparent\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"padding-left:12px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(130, 117, 255, 87);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    background-color: rgba(187, 170, 254,150);\n"
"    color: rgba(255, 255, 255,255);\n"
"border-left: 2px solid rgb(255, 255, 255)\n"
"\n"
"\n"
"}\n"
"")
        self.listWidget_dynamic.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_dynamic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_dynamic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_dynamic.setAutoScrollMargin(16)
        self.listWidget_dynamic.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_dynamic.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_dynamic.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_dynamic.setMovement(QtWidgets.QListView.Static)
        self.listWidget_dynamic.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_dynamic.setProperty("isWrapping", False)
        self.listWidget_dynamic.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_dynamic.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_dynamic.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_dynamic.setModelColumn(0)
        self.listWidget_dynamic.setBatchSize(100)
        self.listWidget_dynamic.setProperty("IconSize", QtCore.QSize(128, 128))
        self.listWidget_dynamic.setObjectName("listWidget_dynamic")
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/感应锁_induction-lock.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget_dynamic.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/上课铃_bell-ring.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listWidget_dynamic.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/思考问题_thinking-problem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listWidget_dynamic.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/程序问题_bug.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listWidget_dynamic.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/保存硬盘_save-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listWidget_dynamic.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_dynamic)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 4)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 4)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame#frame_4{border-top-left-radius:0px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"\n"
"    background-color: rgb(241, 244, 249)\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_code = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_code.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_code.setFont(font)
        self.lineEdit_code.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"margin-left:12px;\n"
"border:none;")
        self.lineEdit_code.setClearButtonEnabled(True)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.horizontalLayout_4.addWidget(self.lineEdit_code)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(186, 186, 186);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_level = QtWidgets.QLabel(self.frame_5)
        self.label_level.setStyleSheet("color: rgb(186, 186, 186);")
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_5.addWidget(self.label_level)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line.setStyleSheet("background-color: rgb(241, 244, 249)")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_12.addWidget(self.frame_5)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_19 = QtWidgets.QFrame(self.frame_4)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_show = QtWidgets.QFrame(self.frame_19)
        self.frame_show.setStyleSheet("QFrame#frame_6{border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:0px;\n"
"    background-color: rgb(241, 244, 249);\n"
"\n"
"}")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        #self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_show)
        #self.verticalLayout_11.setContentsMargins(-1, 24, -1, -1)
        #self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3.addWidget(self.frame_show)
        self.horizontalLayout_12.addWidget(self.frame_19)
        self.frame_changeHor = QtWidgets.QFrame(self.frame_4)
        self.frame_changeHor.setMinimumSize(QtCore.QSize(21, 0))
        self.frame_changeHor.setMaximumSize(QtCore.QSize(21, 16777215))
        self.frame_changeHor.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.frame_changeHor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_changeHor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_changeHor.setObjectName("frame_changeHor")
        self.horizontalLayout_12.addWidget(self.frame_changeHor)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_changeVer = QtWidgets.QFrame(self.frame_4)
        self.frame_changeVer.setMinimumSize(QtCore.QSize(0, 21))
        self.frame_changeVer.setMaximumSize(QtCore.QSize(16777215, 21))
        self.frame_changeVer.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.frame_changeVer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_changeVer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_changeVer.setObjectName("frame_changeVer")
        self.horizontalLayout_13.addWidget(self.frame_changeVer)
        self.frame_changerAll = QtWidgets.QFrame(self.frame_4)
        self.frame_changerAll.setMinimumSize(QtCore.QSize(21, 21))
        self.frame_changerAll.setMaximumSize(QtCore.QSize(21, 21))
        self.frame_changerAll.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.frame_changerAll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_changerAll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_changerAll.setObjectName("frame_changerAll")
        self.horizontalLayout_13.addWidget(self.frame_changerAll)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 10)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_20.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.listWidget_static.setCurrentRow(-1)
        self.listWidget_dynamic.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_theme.setText(_translate("MainWindow", "监控软件"))
        self.listWidget_static.setSortingEnabled(False)
        __sortingEnabled = self.listWidget_static.isSortingEnabled()
        self.listWidget_static.setSortingEnabled(False)
        item = self.listWidget_static.item(0)
        item.setText(_translate("MainWindow", "主页"))
        item = self.listWidget_static.item(1)
        item.setText(_translate("MainWindow", "车辆管理"))
        item = self.listWidget_static.item(2)
        item.setText(_translate("MainWindow", "数据可视化"))
        item = self.listWidget_static.item(3)
        item.setText(_translate("MainWindow", "环境监测"))
        self.listWidget_static.setSortingEnabled(__sortingEnabled)
        self.label_realtime.setText(_translate("MainWindow", "实时监测"))
        self.listWidget_dynamic.setSortingEnabled(False)
        __sortingEnabled = self.listWidget_dynamic.isSortingEnabled()
        self.listWidget_dynamic.setSortingEnabled(False)
        item = self.listWidget_dynamic.item(0)
        item.setText(_translate("MainWindow", "实时定位"))
        item = self.listWidget_dynamic.item(1)
        item.setText(_translate("MainWindow", "实时位姿"))
        item = self.listWidget_dynamic.item(2)
        item.setText(_translate("MainWindow", "远程控制"))

        self.listWidget_dynamic.setSortingEnabled(__sortingEnabled)
        self.lineEdit_code.setPlaceholderText(_translate("MainWindow", "请输入权限密码"))
        self.label_3.setText(_translate("MainWindow", "Level："))
        self.label_level.setText(_translate("MainWindow", "管理员"))
# import resources_rc
