# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MangeWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 569)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_whole = QtWidgets.QFrame(Form)
        self.frame_whole.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_whole.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_whole.setObjectName("frame_whole")
        self.frame_carType = QtWidgets.QFrame(self.frame_whole)
        self.frame_carType.setGeometry(QtCore.QRect(430, 10, 361, 241))
        self.frame_carType.setStyleSheet("QFrame#frame_carType{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(255,255,255);\n"
"\n"
"}")
        self.frame_carType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carType.setObjectName("frame_carType")
        self.label_carImg = QtWidgets.QLabel(self.frame_carType)
        self.label_carImg.setGeometry(QtCore.QRect(180, 20, 161, 101))
        self.label_carImg.setText("")
        self.label_carImg.setObjectName("label_carImg")
        self.label_one = QtWidgets.QLabel(self.frame_carType)
        self.label_one.setGeometry(QtCore.QRect(10, 140, 60, 16))
        self.label_one.setObjectName("label_one")
        self.label_two = QtWidgets.QLabel(self.frame_carType)
        self.label_two.setGeometry(QtCore.QRect(10, 170, 60, 16))
        self.label_two.setObjectName("label_two")
        self.label_three = QtWidgets.QLabel(self.frame_carType)
        self.label_three.setGeometry(QtCore.QRect(10, 200, 60, 16))
        self.label_three.setObjectName("label_three")
        self.btn_delete = QtWidgets.QPushButton(self.frame_carType)
        self.btn_delete.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.btn_delete.setStyleSheet("QPushButton#btn_delete{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(219, 181, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"      text-align: center center;\n"
"} \n"
"/*鼠标放在按钮上方*/\n"
"QPushButton#btn_delete:hover {\n"
"    background-color: rgba(219, 181, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"} \n"
"QPushButton#btn_delete:pressed {\n"
"    background-color: rgba(219, 181, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"} ")
        self.btn_delete.setText("")
        self.btn_delete.setObjectName("btn_delete")
        self.label_typeLocation = QtWidgets.QLabel(self.frame_carType)
        self.label_typeLocation.setGeometry(QtCore.QRect(10, 40, 191, 21))
        self.label_typeLocation.setObjectName("label_typeLocation")
        self.label_locationIcon = QtWidgets.QLabel(self.frame_carType)
        self.label_locationIcon.setGeometry(QtCore.QRect(120, 40, 21, 21))
        self.label_locationIcon.setText("")
        self.label_locationIcon.setObjectName("label_locationIcon")
        self.label_typeBattery = QtWidgets.QLabel(self.frame_carType)
        self.label_typeBattery.setGeometry(QtCore.QRect(10, 70, 161, 16))
        self.label_typeBattery.setObjectName("label_typeBattery")
        self.label_typeVersion = QtWidgets.QLabel(self.frame_carType)
        self.label_typeVersion.setGeometry(QtCore.QRect(10, 100, 171, 16))
        self.label_typeVersion.setObjectName("label_typeVersion")
        self.progressBar_one = QtWidgets.QProgressBar(self.frame_carType)
        self.progressBar_one.setGeometry(QtCore.QRect(90, 140, 231, 16))
        self.progressBar_one.setStyleSheet("QProgressBar::chunk {\n"
"        border-top-left-radius:8px;\n"
"border-bottom-left-radius:8px;\n"
"    background-color: rgb(103, 216, 217)\n"
"}\n"
"QProgressBar{\n"
"border-radius:8px;\n"
"background-color: rgb(223, 223, 223);\n"
"}")
        self.progressBar_one.setProperty("value", 24)
        self.progressBar_one.setObjectName("progressBar_one")
        self.progressBar_two = QtWidgets.QProgressBar(self.frame_carType)
        self.progressBar_two.setGeometry(QtCore.QRect(90, 170, 231, 16))
        self.progressBar_two.setStyleSheet("QProgressBar::chunk {\n"
"        border-top-left-radius:8px;\n"
"border-bottom-left-radius:8px;\n"
"    background-color: rgb(219, 181, 255)\n"
"}\n"
"QProgressBar{\n"
"border-radius:8px;\n"
"background-color: rgb(223, 223, 223);\n"
"}")
        self.progressBar_two.setProperty("value", 24)
        self.progressBar_two.setObjectName("progressBar_two")
        self.progressBar_three = QtWidgets.QProgressBar(self.frame_carType)
        self.progressBar_three.setGeometry(QtCore.QRect(90, 200, 231, 16))
        self.progressBar_three.setStyleSheet("QProgressBar::chunk {\n"
"        border-top-left-radius:8px;\n"
"border-bottom-left-radius:8px;\n"
"    background-color: rgb(181, 217, 255)\n"
"}\n"
"QProgressBar{\n"
"border-radius:8px;\n"
"background-color: rgb(223, 223, 223);\n"
"}")
        self.progressBar_three.setProperty("value", 24)
        self.progressBar_three.setObjectName("progressBar_three")
        self.frame_carChart = QtWidgets.QFrame(self.frame_whole)
        self.frame_carChart.setGeometry(QtCore.QRect(430, 260, 361, 261))
        self.frame_carChart.setStyleSheet("QFrame#frame_carChart{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(255,255,255);\n"
"\n"
"}")
        self.frame_carChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carChart.setObjectName("frame_carChart")
        self.frame_hardware = QtWidgets.QFrame(self.frame_whole)
        self.frame_hardware.setGeometry(QtCore.QRect(13, 7, 405, 521))
        self.frame_hardware.setStyleSheet("QFrame#frame_hardware{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(240,244,250);\n"
"\n"
"}")
        self.frame_hardware.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hardware.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hardware.setObjectName("frame_hardware")
        self.frame_carHardware = QtWidgets.QFrame(self.frame_hardware)
        self.frame_carHardware.setGeometry(QtCore.QRect(10, 10, 381, 171))
        self.frame_carHardware.setStyleSheet("border:none;")
        self.frame_carHardware.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carHardware.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carHardware.setObjectName("frame_carHardware")
        self.label_carHardware = QtWidgets.QLabel(self.frame_carHardware)
        self.label_carHardware.setGeometry(QtCore.QRect(20, 20, 121, 121))
        self.label_carHardware.setText("")
        self.label_carHardware.setObjectName("label_carHardware")
        self.label = QtWidgets.QLabel(self.frame_carHardware)
        self.label.setGeometry(QtCore.QRect(190, 100, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Hiragino Sans GB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("color:green")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame_hardware)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 190, 381, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_carCamera = QtWidgets.QFrame(self.layoutWidget)
        self.frame_carCamera.setStyleSheet("QFrame#frame_carCamera{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(255,255,255);\n"
"\n"
"}")
        self.frame_carCamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carCamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carCamera.setObjectName("frame_carCamera")
        self.label_carCamera = QtWidgets.QLabel(self.frame_carCamera)
        self.label_carCamera.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_carCamera.setText("")
        self.label_carCamera.setObjectName("label_carCamera")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_carCamera)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 10, 271, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_carCamera1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_carCamera1.setStyleSheet("color:red")
        self.label_carCamera1.setText("")
        self.label_carCamera1.setObjectName("label_carCamera1")
        self.verticalLayout_2.addWidget(self.label_carCamera1)
        self.label_carCamera2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_carCamera2.setStyleSheet("color:green")
        self.label_carCamera2.setText("")
        self.label_carCamera2.setObjectName("label_carCamera2")
        self.verticalLayout_2.addWidget(self.label_carCamera2)
        self.label_carCamera3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_carCamera3.setStyleSheet("color:blue")
        self.label_carCamera3.setText("")
        self.label_carCamera3.setObjectName("label_carCamera3")
        self.verticalLayout_2.addWidget(self.label_carCamera3)
        self.verticalLayout.addWidget(self.frame_carCamera)
        self.frame_carRadar = QtWidgets.QFrame(self.layoutWidget)
        self.frame_carRadar.setStyleSheet("QFrame#frame_carRadar{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(255,255,255);\n"
"\n"
"}")
        self.frame_carRadar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carRadar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carRadar.setObjectName("frame_carRadar")
        self.label_carRadar = QtWidgets.QLabel(self.frame_carRadar)
        self.label_carRadar.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_carRadar.setText("")
        self.label_carRadar.setObjectName("label_carRadar")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_carRadar)
        self.layoutWidget2.setGeometry(QtCore.QRect(100, 10, 271, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_carRadar1 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_carRadar1.setStyleSheet("color:red")
        self.label_carRadar1.setText("")
        self.label_carRadar1.setObjectName("label_carRadar1")
        self.verticalLayout_3.addWidget(self.label_carRadar1)
        self.label_carRadar2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_carRadar2.setStyleSheet("color:green")
        self.label_carRadar2.setText("")
        self.label_carRadar2.setObjectName("label_carRadar2")
        self.verticalLayout_3.addWidget(self.label_carRadar2)
        self.label_carRadar3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_carRadar3.setStyleSheet("color:blue")
        self.label_carRadar3.setText("")
        self.label_carRadar3.setObjectName("label_carRadar3")
        self.verticalLayout_3.addWidget(self.label_carRadar3)
        self.verticalLayout.addWidget(self.frame_carRadar)
        self.frame_carBattery = QtWidgets.QFrame(self.layoutWidget)
        self.frame_carBattery.setStyleSheet("QFrame#frame_carBattery{\n"
"    border:none;\n"
"    border-radius:12px ;\n"
"    background-color:rgb(255,255,255);\n"
"\n"
"}")
        self.frame_carBattery.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carBattery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carBattery.setObjectName("frame_carBattery")
        self.label_carBattery = QtWidgets.QLabel(self.frame_carBattery)
        self.label_carBattery.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_carBattery.setText("")
        self.label_carBattery.setObjectName("label_carBattery")
        self.textBro_carBattery = QtWidgets.QTextBrowser(self.frame_carBattery)
        self.textBro_carBattery.setGeometry(QtCore.QRect(80, 10, 281, 71))
        self.textBro_carBattery.setStyleSheet("border:none;\n"
"border-radius:12px ;\n"
"background-color:rgb(255,255,255)")
        self.textBro_carBattery.setObjectName("textBro_carBattery")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_carBattery)
        self.layoutWidget_3.setGeometry(QtCore.QRect(100, 10, 271, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_carBattery1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_carBattery1.setStyleSheet("color:red")
        self.label_carBattery1.setText("")
        self.label_carBattery1.setObjectName("label_carBattery1")
        self.verticalLayout_5.addWidget(self.label_carBattery1)
        self.label_carBattery2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_carBattery2.setStyleSheet("color:green")
        self.label_carBattery2.setText("")
        self.label_carBattery2.setObjectName("label_carBattery2")
        self.verticalLayout_5.addWidget(self.label_carBattery2)
        self.label_carBattery3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_carBattery3.setStyleSheet("color:blue")
        self.label_carBattery3.setText("")
        self.label_carBattery3.setObjectName("label_carBattery3")
        self.verticalLayout_5.addWidget(self.label_carBattery3)
        self.verticalLayout.addWidget(self.frame_carBattery)
        self.horizontalLayout.addWidget(self.frame_whole)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_one.setText(_translate("Form", "TextLabel"))
        self.label_two.setText(_translate("Form", "TextLabel"))
        self.label_three.setText(_translate("Form", "TextLabel"))
        self.label_typeLocation.setText(_translate("Form", "Jinlin university "))
        self.label_typeBattery.setText(_translate("Form", "电量：30%"))
        self.label_typeVersion.setText(_translate("Form", "版本：V 1.0"))
        self.label.setText(_translate("Form", "硬件配置"))
